import { AppHeader } from "@/components/AppHeader";
import { Button } from "@/components/ui/button";
import { trpc } from "@/lib/trpc";
import { Accessibility, ArrowRight, BrainCircuit, ChartNoAxesCombined, CirclePlay, Compass, GraduationCap, HeartHandshake, Lightbulb, Rocket, Trophy } from "lucide-react";
import { Link } from "wouter";

const heroImage = "/manus-storage/edusphere-instructor_80a2feb5.jpg";

export default function About() {
  const categories = trpc.catalog.categories.useQuery();
  const catalog = trpc.catalog.list.useQuery();
  const instructors = trpc.catalog.instructors.useQuery();
  const stats = [
    { value: catalog.data?.length ?? "—", label: "Learning paths" },
    { value: categories.data?.length ?? "—", label: "Skill disciplines" },
    { value: instructors.data?.length ?? "—", label: "Expert instructors" },
    { value: catalog.data ? `${Math.round(catalog.data.reduce((total: number, item: any) => total + (item.course.durationMinutes || 0), 0) / 60)}h` : "—", label: "Learning content" },
  ];
  const benefits = [
    { icon: CirclePlay, title: "Learn at your pace", copy: "Access structured courses and make steady progress whenever the moment is right." },
    { icon: BrainCircuit, title: "AI-powered learning", copy: "Use thoughtful study prompts and on-demand guidance when you need a clearer next step." },
    { icon: ChartNoAxesCombined, title: "Track your progress", copy: "See your learning journey take shape through milestones, assessments, and visible momentum." },
    { icon: Trophy, title: "Earn certificates", copy: "Complete meaningful work and carry a record of your achievement into your next opportunity." },
  ];
  const values = [
    { icon: Accessibility, title: "Accessibility", copy: "High-quality learning should be within reach, not behind unnecessary complexity." },
    { icon: Compass, title: "Practical learning", copy: "We believe ideas become useful when they are practiced, applied, and reflected on." },
    { icon: Rocket, title: "Continuous growth", copy: "Every small, deliberate learning session can become the foundation for real progress." },
    { icon: Lightbulb, title: "Innovation", copy: "We pair timeless teaching craft with tools that help learners stay curious and capable." },
  ];
  return <div className="app-shell min-h-screen"><AppHeader /><main>
    <section className="relative overflow-hidden bg-[#0f355a] text-white"><div className="absolute inset-0 opacity-80 [background-image:radial-gradient(circle_at_18%_5%,rgba(105,193,232,.34),transparent_22%),radial-gradient(circle_at_92%_75%,rgba(233,190,95,.24),transparent_25%)]" /><div className="container relative grid gap-12 py-18 lg:grid-cols-[1.04fr_.96fr] lg:items-center lg:py-24"><div><p className="page-kicker text-[#a9d8f3]">A more intentional education company</p><h1 className="mt-5 max-w-3xl font-display text-5xl font-bold leading-[.98] tracking-tight sm:text-6xl">Empowering learners to build their future.</h1><p className="mt-7 max-w-xl text-lg leading-8 text-slate-200">EduSphere is a modern learning platform designed to make high-quality education more accessible, engaging, and personalized.</p><div className="mt-9 flex flex-wrap gap-3"><Link href="/courses"><Button size="lg" className="rounded-xl bg-white text-[#143a61] hover:bg-[#eaf5fb]">Explore courses <ArrowRight className="ml-2 h-4 w-4" /></Button></Link><Link href="/ai-tutor"><Button size="lg" variant="outline" className="rounded-xl border-white/30 bg-white/5 text-white hover:bg-white/10 hover:text-white">Try AI Study Assistant</Button></Link></div></div><div className="relative"><div className="absolute -inset-5 rounded-[2.5rem] border border-white/15" /><div className="relative overflow-hidden rounded-[2rem] border border-white/20 bg-white/10 p-3 shadow-2xl"><img src={heroImage} alt="EduSphere educator" className="aspect-[4/3.6] w-full rounded-[1.5rem] object-cover" /><div className="absolute bottom-7 left-7 right-7 rounded-2xl border border-white/20 bg-[#0f355ae8] p-4 backdrop-blur"><p className="text-xs font-bold uppercase tracking-[.14em] text-[#f4d789]">Made for momentum</p><p className="mt-1 font-display text-xl">Learning that stays with you.</p></div></div></div></div></section>
    <section className="container py-18"><div className="grid gap-12 lg:grid-cols-[1.08fr_.92fr] lg:items-center"><div><p className="page-kicker">Our story</p><h2 className="mt-3 max-w-xl font-display text-4xl font-bold leading-tight text-[#143a61]">A platform built around the practice of learning.</h2><p className="mt-6 max-w-xl text-base leading-8 text-slate-600">EduSphere was created with a simple idea: learning should be practical, accessible, and personalized. We bring structured courses, interactive learning, progress tracking, and AI-powered assistance together in one focused platform.</p><p className="mt-4 max-w-xl text-base leading-8 text-slate-600">The result is a calmer digital space where learners can build capability at their own pace—and educators can share knowledge with intention.</p></div><div className="rounded-[2rem] bg-[#e8f4fb] p-8 shadow-[0_22px_55px_rgba(18,54,91,.10)]"><HeartHandshake className="h-8 w-8 text-[#1670a8]" /><p className="mt-8 font-display text-3xl font-bold leading-tight text-[#143a61]">Clear paths. Meaningful practice. Visible progress.</p><div className="mt-8 grid grid-cols-2 gap-3">{stats.slice(0,2).map((item) => <div className="rounded-2xl bg-white p-4" key={item.label}><p className="font-display text-3xl font-bold text-[#143a61]">{item.value}</p><p className="mt-1 text-xs font-semibold text-slate-500">{item.label}</p></div>)}</div></div></div></section>
    <section className="bg-[#143a61] py-18 text-white"><div className="container"><p className="page-kicker text-[#a9d8f3]">Our mission</p><div className="mt-4 grid gap-10 lg:grid-cols-[.8fr_1.2fr]"><h2 className="font-display text-5xl font-bold leading-[.98]">Learning without limits.</h2><div className="rounded-3xl border border-white/15 bg-white/8 p-7"><p className="text-lg leading-8 text-slate-200">EduSphere helps learners develop practical skills, learn at their own pace, and prepare for real-world opportunities. We believe a better learning platform should make ambition feel more approachable—not more overwhelming.</p><div className="mt-8 flex items-center gap-3 text-sm font-semibold text-[#f4d789]"><GraduationCap className="h-5 w-5" />A focused place to grow your next capability.</div></div></div></div></section>
    <section className="container py-18"><div className="max-w-2xl"><p className="page-kicker">Why EduSphere</p><h2 className="mt-3 font-display text-4xl font-bold text-[#143a61]">Designed for learning that fits real life.</h2></div><div className="mt-9 grid gap-5 md:grid-cols-2 lg:grid-cols-4">{benefits.map((item) => <article className="surface-card group rounded-3xl p-6 transition duration-300 hover:-translate-y-1 hover:border-[#9fc8df]" key={item.title}><span className="grid h-11 w-11 place-items-center rounded-2xl bg-[#e5f3fb] text-[#1670a8]"><item.icon className="h-5 w-5" /></span><h3 className="mt-6 text-lg font-bold text-[#143a61]">{item.title}</h3><p className="mt-3 text-sm leading-6 text-slate-600">{item.copy}</p></article>)}</div></section>
    <section className="border-y border-slate-200 bg-white"><div className="container grid gap-5 py-12 sm:grid-cols-2 lg:grid-cols-4">{stats.map((item) => <div className="text-center" key={item.label}><p className="font-display text-4xl font-bold text-[#143a61]">{item.value}</p><p className="mt-2 text-sm font-semibold text-slate-500">{item.label}</p></div>)}</div></section>
    <section className="container py-18"><div className="max-w-2xl"><p className="page-kicker">What we believe in</p><h2 className="mt-3 font-display text-4xl font-bold text-[#143a61]">The values behind every learning path.</h2></div><div className="mt-9 grid gap-5 md:grid-cols-2">{values.map((item) => <article className="rounded-3xl border border-slate-200 bg-white p-7 shadow-[0_12px_35px_rgba(23,39,62,.05)]" key={item.title}><item.icon className="h-6 w-6 text-[#b6812b]" /><h3 className="mt-5 font-display text-2xl font-bold text-[#143a61]">{item.title}</h3><p className="mt-3 max-w-md leading-7 text-slate-600">{item.copy}</p></article>)}</div></section>
    <section className="container pb-20"><div className="relative overflow-hidden rounded-[2rem] bg-[#d6b26c] px-7 py-14 text-center shadow-[0_25px_50px_rgba(145,102,27,.18)] md:px-14"><div className="absolute inset-0 opacity-40 [background-image:radial-gradient(rgba(20,58,97,.22)_1px,transparent_1px)] [background-size:15px_15px]" /><div className="relative"><p className="page-kicker text-[#68420e]">Your next chapter starts here</p><h2 className="mt-4 font-display text-4xl font-bold text-[#143a61]">Ready to start learning?</h2><p className="mx-auto mt-4 max-w-xl leading-7 text-[#143a61]/80">Explore courses, build new skills, and take your learning journey further with EduSphere.</p><div className="mt-8 flex flex-wrap justify-center gap-3"><Link href="/courses"><Button className="rounded-xl bg-[#143a61] px-6">Explore Courses <ArrowRight className="ml-2 h-4 w-4" /></Button></Link><Link href="/ai-tutor"><Button variant="outline" className="rounded-xl border-[#143a61]/25 bg-white/50 px-6 text-[#143a61] hover:bg-white">Try AI Study Assistant</Button></Link></div></div></div></section>
  </main></div>;
}
