import { AppHeader } from "@/components/AppHeader";
import { Avatar, AvatarFallback } from "@/components/ui/avatar";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import { useAuth } from "@/_core/hooks/useAuth";
import { trpc } from "@/lib/trpc";
import { FormEvent, useState } from "react";
import { toast } from "sonner";
import { Link } from "wouter";

export default function Profile() { const { user, loading } = useAuth(); const [name, setName] = useState(""); const [headline, setHeadline] = useState(""); const [bio, setBio] = useState(""); const profile = trpc.account.profile.useQuery(undefined, { enabled: Boolean(user) }); const utils = trpc.useUtils(); const update = trpc.account.updateProfile.useMutation({ onSuccess: () => { toast.success("Profile updated."); utils.account.profile.invalidate(); }, onError: (error) => toast.error(error.message) }); const chooseRole = trpc.account.chooseLearningRole.useMutation({ onSuccess: () => { toast.success("Your role is updated. Refreshing your workspace."); window.location.assign("/portal"); }, onError: (error) => toast.error(error.message) }); const current: any = profile.data ?? user;
  const submit = (event: FormEvent) => { event.preventDefault(); update.mutate({ name: name || current?.name || undefined, headline: headline || current?.headline || null, bio: bio || current?.bio || null }); }; if (loading || profile.isLoading) return <div className="min-h-screen bg-[#fdfbf5]"><AppHeader /></div>; if (!user) return <div className="min-h-screen bg-[#fdfbf5]"><AppHeader /><div className="container py-24 text-center">Sign in to manage your profile.</div></div>;
  return <div className="min-h-screen bg-[#fdfbf5]"><AppHeader /><main className="container max-w-3xl py-12"><Link href="/portal" className="text-sm font-semibold text-[#173352]">← Back to workspace</Link><div className="mt-6 rounded-[1.5rem] bg-white p-6 shadow-lift md:p-8"><div className="flex items-center gap-4"><Avatar className="h-16 w-16"><AvatarFallback className="bg-[#d6b26c] text-xl font-bold text-[#173352]">{current?.name?.slice(0,1)?.toUpperCase() || "E"}</AvatarFallback></Avatar><div><p className="eyebrow">Account</p><h1 className="font-display text-3xl font-bold text-[#173352]">Your profile</h1></div></div><form className="mt-8" onSubmit={submit}><div><Label htmlFor="profileName">Name</Label><Input id="profileName" defaultValue={current?.name || ""} onChange={(event) => setName(event.target.value)} className="mt-2" /></div><div className="mt-5"><Label htmlFor="headline">Headline</Label><Input id="headline" defaultValue={current?.headline || ""} onChange={(event) => setHeadline(event.target.value)} placeholder="e.g. Curious lifelong learner" className="mt-2" /></div><div className="mt-5"><Label htmlFor="bio">About you</Label><Textarea id="bio" defaultValue={current?.bio || ""} onChange={(event) => setBio(event.target.value)} className="mt-2 min-h-28" /></div><Button type="submit" disabled={update.isPending} className="mt-6 bg-[#173352]">{update.isPending ? "Saving…" : "Save profile"}</Button></form>{current?.role !== "admin" && <div className="mt-10 border-t border-slate-100 pt-8"><p className="eyebrow">Learning role</p><h2 className="mt-2 font-display text-2xl font-bold text-[#173352]">How will you use EduSphere?</h2><p className="mt-2 text-sm leading-6 text-slate-600">You can switch between a learner and an instructor workspace as your focus changes.</p><div className="mt-5 flex flex-wrap gap-3"><Button variant={current?.role === "student" ? "default" : "outline"} className={current?.role === "student" ? "bg-[#173352]" : ""} onClick={() => chooseRole.mutate({ role: "student" })}>I’m learning</Button><Button variant={current?.role === "instructor" ? "default" : "outline"} className={current?.role === "instructor" ? "bg-[#173352]" : ""} onClick={() => chooseRole.mutate({ role: "instructor" })}>I’m teaching</Button></div></div>}</div></main></div>; }
