import { Button } from "@/components/ui/button";
import { Progress } from "@/components/ui/progress";
import { RadioGroup, RadioGroupItem } from "@/components/ui/radio-group";
import { trpc } from "@/lib/trpc";
import { CheckCircle2, ChevronLeft, RotateCcw, XCircle } from "lucide-react";
import { useState } from "react";
import { Link, useRoute } from "wouter";

export default function Quiz() { const [, params] = useRoute("/quiz/:quizId"); const quizId = Number(params?.quizId); const quiz = trpc.quiz.get.useQuery({ quizId }, { enabled: Boolean(quizId) }); const [answers, setAnswers] = useState<Record<number, number>>({}); const submit = trpc.quiz.submit.useMutation(); const data: any = quiz.data; const result: any = submit.data;
  if (quiz.isLoading) return <div className="grid min-h-screen place-items-center bg-[#f8f6f1]">Loading assessment…</div>; if (!data) return <div className="grid min-h-screen place-items-center bg-[#f8f6f1]"><Link href="/portal"><Button>Return to workspace</Button></Link></div>;
  if (result) return <div className="min-h-screen bg-[#f8f6f1] px-5 py-12"><div className="mx-auto max-w-3xl"><Link href={`/learn/${result.completion.courseId || data.quiz.courseId}`} className="text-sm font-semibold text-[#173352]">← Back to course</Link><div className="mt-6 rounded-[1.5rem] bg-white p-7 shadow-lift md:p-10"><div className={`grid h-16 w-16 place-items-center rounded-full ${result.passed ? "bg-[#e2f0e7] text-[#297054]" : "bg-[#fce8e6] text-[#b93e38]"}`}>{result.passed ? <CheckCircle2 className="h-8 w-8" /> : <XCircle className="h-8 w-8" />}</div><p className="eyebrow mt-6">Assessment complete</p><h1 className="mt-2 font-display text-4xl font-bold text-[#173352]">{result.percentage}%</h1><p className="mt-2 text-slate-600">You scored {result.score} out of {result.maxScore}. {result.passed ? "You met the passing threshold." : `A score of ${result.passingScore}% is required. You can retry whenever you’re ready.`}</p><div className="mt-8 space-y-4">{result.review.map((item: any, index: number) => <div key={item.id} className="rounded-xl border border-slate-100 p-4"><div className="flex gap-3"><span className="text-xs font-bold text-[#b6812b]">{index + 1}</span><div><p className="font-semibold text-slate-800">{item.question}</p><p className="mt-2 text-sm text-slate-500">{item.selectedOption === item.correctOption ? "Correct" : `Correct answer: ${item.options[item.correctOption]}`}</p>{item.explanation && <p className="mt-2 text-sm leading-6 text-slate-600">{item.explanation}</p>}</div></div></div>)}</div>{!result.passed && <Button className="mt-7 bg-[#173352]" onClick={() => { submit.reset(); setAnswers({}); }}><RotateCcw className="mr-2 h-4 w-4" />Try again</Button>}</div></div></div>;
  const completed = Object.keys(answers).length; return <div className="min-h-screen bg-[#f8f6f1] px-5 py-10"><div className="mx-auto max-w-3xl"><Link href={`/learn/${data.quiz.courseId}`} className="inline-flex items-center text-sm font-semibold text-[#173352]"><ChevronLeft className="mr-1 h-4 w-4" />Back to course</Link><div className="mt-6 rounded-[1.5rem] bg-white p-6 shadow-lift md:p-9"><p className="eyebrow">Assessment</p><h1 className="mt-2 font-display text-4xl font-bold text-[#173352]">{data.quiz.title}</h1><p className="mt-3 leading-7 text-slate-600">{data.quiz.description || "Choose the best answer for each question."}</p>{data.attempts?.length ? <div className="mt-5 rounded-xl bg-[#f1eee5] p-4"><p className="text-xs font-bold uppercase tracking-[.12em] text-[#9b6416]">Your previous attempts</p><div className="mt-2 flex flex-wrap gap-2">{data.attempts.map((attempt: any) => <span className="rounded-full bg-white px-3 py-1 text-sm font-semibold text-[#173352]" key={attempt.id}>{attempt.percentage}% · {new Date(attempt.submittedAt).toLocaleDateString()}</span>)}</div></div> : null}<div className="mt-6 flex items-center gap-3"><Progress value={(completed / data.questions.length) * 100} className="h-2" /><span className="shrink-0 text-xs font-semibold text-slate-500">{completed}/{data.questions.length}</span></div><div className="mt-8 space-y-9">{data.questions.map((question: any, index: number) => <fieldset key={question.id}><legend className="font-semibold leading-6 text-slate-800"><span className="mr-2 text-[#b6812b]">{index + 1}.</span>{question.question}</legend><RadioGroup value={answers[question.id] === undefined ? undefined : String(answers[question.id])} onValueChange={(value) => setAnswers((current) => ({ ...current, [question.id]: Number(value) }))} className="mt-4 gap-3">{question.options.map((option: string, optionIndex: number) => <label key={optionIndex} className="flex cursor-pointer items-center gap-3 rounded-xl border border-slate-200 px-4 py-3 text-sm hover:border-[#b6812b]/50"><RadioGroupItem value={String(optionIndex)} />{option}</label>)}</RadioGroup></fieldset>)}</div><Button disabled={completed !== data.questions.length || submit.isPending} className="mt-8 bg-[#173352]" onClick={() => submit.mutate({ quizId, answers: Object.entries(answers).map(([questionId, selectedOption]) => ({ questionId: Number(questionId), selectedOption })) })}>{submit.isPending ? "Grading your answers…" : "Submit assessment"}</Button>{submit.error && <p className="mt-3 text-sm text-red-600">{submit.error.message}</p>}</div></div></div>; }
