/**
 * Catch-all Vercel Function for tRPC, OAuth, Stripe, and storage-proxy routes.
 * Its dependency is generated by the normal build in JavaScript so Vercel does
 * not re-type-check the TypeScript application graph while packaging the
 * serverless function.
 */
import app from "../dist/vercelApp.js";

export default app;
